# Generated by Django 2.1.1 on 2019-02-03 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailFunding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(default='Not Mentioned')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=40)),
                ('p_description', models.CharField(max_length=40)),
                ('p_github', models.CharField(max_length=100)),
                ('p_recommendation_pic_path', models.FileField(blank=True, null=True, upload_to='')),
                ('p_domain', models.CharField(max_length=100)),
                ('p_efund', models.CharField(max_length=100)),
                ('p_afund', models.CharField(default='0', max_length=100)),
                ('p_startdate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=40)),
                ('github', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('pic_path', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='detailfunding',
            name='student',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
